# Generated by Django 2.2.2 on 2019-06-25 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rut',
        ),
    ]
