# Generated by Django 2.2.2 on 2019-06-25 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(default='default', max_length=20)),
                ('last_name', models.CharField(default='default', max_length=20)),
                ('email', models.EmailField(default='default', max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('tarjeta', models.IntegerField(default='0')),
                ('banco', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=6)),
                ('marca', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=10)),
                ('año', models.IntegerField(default='null')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiEstacionamiento.Usuario')),
            ],
        ),
    ]
