# Generated by Django 2.2.2 on 2019-06-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiEstacionamiento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
