# Generated by Django 2.2.2 on 2019-06-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiEstacionamiento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
