# Generated by Django 2.2.2 on 2019-06-25 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiEstacionamiento', '0002_remove_usuario_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='password',
            new_name='contra',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='correo',
        ),
    ]
