# Generated by Django 2.2.2 on 2019-06-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiEstacionamiento', '0003_auto_20190625_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('valor', models.IntegerField(default='0')),
            ],
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='usuario',
        ),
    ]
