# Generated by Django 2.2.2 on 2019-06-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiEstacionamiento', '0004_auto_20190625_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrendador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='default', max_length=20)),
                ('last_name', models.CharField(default='default', max_length=20)),
                ('correo', models.EmailField(default='default', max_length=20)),
                ('contra', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('tarjeta', models.IntegerField(default='0')),
                ('banco', models.CharField(max_length=20)),
            ],
        ),
    ]
