# Generated by Django 2.2.2 on 2019-06-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiEstacionamiento', '0005_arrendador'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrendador',
            name='rut',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='rut',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rut',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='rut',
            field=models.IntegerField(default='0'),
        ),
    ]
